//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetintAIFormlar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalistayDb
    {
        public int Id { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string kurumu { get; set; }
        public string gorevi { get; set; }
        public string unvani { get; set; }
        public string katilim { get; set; }
        public string telefon { get; set; }
        public string mail { get; set; }
    }
}
