//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetintAIFormlar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FormEntities : DbContext
    {
        public FormEntities()
            : base("name=FormEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalistayDb> CalistayDb { get; set; }
        public virtual DbSet<DoktorDb> DoktorDb { get; set; }
        public virtual DbSet<IletisimDb> IletisimDb { get; set; }
        public virtual DbSet<KurulusDb> KurulusDb { get; set; }
        public virtual DbSet<RobotDb> RobotDb { get; set; }
        public virtual DbSet<UyeDb> UyeDb { get; set; }
    }
}
