//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetintAIFormlar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoktorDb
    {
        public int ID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Unvani { get; set; }
        public string Kurumu { get; set; }
        public string Gorevi { get; set; }
        public string UzmanlikA { get; set; }
        public string SabitT { get; set; }
        public string DahiliT { get; set; }
        public string Mail { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
    }
}
