//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetintAIFormlar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KurulusDb
    {
        public int Id { get; set; }
        public string kurumadi { get; set; }
        public string adresi { get; set; }
        public string bolumleri { get; set; }
        public string telefon { get; set; }
        public string bashekim { get; set; }
        public string adsoyad { get; set; }
        public string scep { get; set; }
        public string sabit { get; set; }
        public string mail { get; set; }
    }
}
