//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetintAIFormlar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RobotDb
    {
        public int id { get; set; }
        public string name { get; set; }
        public string company { get; set; }
        public string lastname { get; set; }
        public string mail { get; set; }
        public string phone { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string adress { get; set; }
        public string message { get; set; }
    }
}
